name: Build

on:
  push:
    branches: [ "master", "dev/*" ]
  pull_request:
    branches: [ "master", "dev/*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: plugin-jars
          path: |
            Core/build/libs/*.jar
            API/build/libs/*.jar
